### ISSUE TITLE
Changes to ~/.config/neofetch/config.conf doesn't work even when forcing with -c.

### ISSUE THREAD

**Issue by TheDunkShot** [MrPotatoBobx/FetchCord#105]
# Debug info
```
----testing.py----
----DE/WM----

deid: N/A
wmid: N/A

----TERMINAL/SHELL----

termid: N/A
shellid: unknown

----HOST INFO----

hostid: o

----GPU INFO----

gpuvendor: N/A

----CPU INFO----

cpumodel: N/A

Connecting
----run_rpc----

uptime in epoch: 1604190247.0
cpuid: 740809641545564170
cpuappid: 742887089179197462
termappid: 745691250186911796
hostappid: 742887089179197462
Packages: N/A
('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
RPC Connection Successful.
cycle 0
appid: 740809641545564170

```
# Operating system & way of installation
EndeavourOS,
AUR,
yay -S fetchcord-git

# Error/issue
Editing ~/.config/neofetch/config.conf and commiting changes to the .conf file, even when forcing with fetchcord -c ~/.config/neofetch/config.conf, didn't change how information is displayed on Discord.

**Comment by BlivionIaG** [comment]
Hello, do you still have this issue when running with fetchcord 2.7.0 ? The way the informations are fetched is different now.

**Comment by MrPotatoBobx** [comment]
i reccomend pip, and try 2.7

**Comment by MrPotatoBobx** [comment]
Closing the issue, reopen if it still occurs.
