### ISSUE TITLE
Allow fetchcord to be run so that the terminal can be closed after running it

### ISSUE THREAD

**Issue by Adora16** [MrPotatoBobx/FetchCord#11]

**Comment by cheeesy** [comment]
Depending on your shell, you can interrupt the process (^Z/CTRL+Z in bash) and then move it to background or disown the process.

**Comment by Adora16** [comment]
I tried disowning it by following the command with an ampersand, but that disconnected it.

**Comment by Hyper-KVM** [comment]
should be possible now.

**Comment by Hyper-KVM** [comment]
closing since it can be done.
