### ISSUE TITLE
everything outputs as N/A, connects normally

### ISSUE THREAD

**Issue by memejim8** [MrPotatoBobx/FetchCord#110]
installed using aur, neofetch runs fine but fetchcord doesnt detect anything

--debug log:

----out.py----

----DE/WM----
deid: N/A
wmid: N/A
wmline item 0: ['WM: N/A']

----TERMINAL----

fontline: ['Font: N/A']
termid: N/A
termline item 0: Terminal: N/A
themeline: Theme: N/A

----HOST INFO----

hostline: Host: N/A
batteryline: Battery: N/A
resline: Resolution: N/A

----GPU INFO----

gpuinfo: GPU: N/A
gpuvendor: N/A

----CPU INFO----

cpuvendor: N/A
cpumodel: N/A
cpuinfo: CPU: N/A
cpuline item 0: ['CPU: N/A']
memline: Memory: N/A

----OS INFO----

sysosline: OS: N/A
sysosid: N/A
diskline: Disk: N/A
packagesline item 0: Packages: N/A
Unknown GPU, contact us on github to resolve this.
Unknown DE/WM, contact us on github to resolve this.
Unknown shell, contact us on github to resolve this.
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact us on the GitHub page to resolve this.(keyerror)

----testing.py----
----DE/WM----

deid: N/A
wmid: N/A

----TERMINAL/SHELL----

termid: N/A
shellid: unknown

----HOST INFO----

hostid: o

----GPU INFO----

gpuvendor: N/A

----CPU INFO----

cpumodel: N/A

**Comment by BlivionIaG** [comment]
Hi, what version are you using ? and how did you installed it ?

**Comment by memejim8** [comment]
> Hi, what version are you using ? and how did you installed it ?

i am using the lastest git version, installed from aur

**Comment by BlivionIaG** [comment]
Ok is it possible to get your neofetch output ? ```neofetch --stdout```. Otherwise i would be interested if you can try the v2.7.0 who is currently on the 2.7 branch. We also have a discord.

**Comment by memejim8** [comment]
neofetch --stdout:

meme@arch
---------
OS >>  Arch Linux x86_64
Host >>  B450M DS3H
Kernel >>  5.9.8-arch1-1
Uptime >>  16 mins
Packages >>  1718 (pacman), 23 (flatpak)
Shell >>  bash 5.0.18
Resolution >>  1920x1080, 1920x1080
DE >>  Unity
WM >>  Mutter
WM Theme >>  Materia-dark-compact
Theme >>  Plata-Noir [GTK2/3]
Icons >>  ePapirus [GTK2/3]
Terminal >>  alacritty
Terminal Font >>  "Ubuntu Mono derivative Powerline"
CPU >>  AMD Ryzen 7 2700X @ 3.7GHz [65.7°C]
GPU >>  AMD ATI Radeon RX 470/480/570/570X/580/580X/590
Memory >>  4701MiB / 16019MiB (29%)

**Comment by BlivionIaG** [comment]
oh, well the neofetch separator needs to be "OS:" on 2.6.x, i'm interested to see if thats solved for you in 2.7, because if it fails, it loads with a custom neofetch config. I plan to not be dependent on the separator in the future (by searching it in neofetch config)

**Comment by memejim8** [comment]
turns out the problem was indeed the separator, thank you for your help

**Comment by BlivionIaG** [comment]
no problem, i have to test if having a different separator is not a problem on 2.7, if you have other questions or problems don't hesitate to ask (we have a discord for that if you want faster responses).
