### ISSUE TITLE
I don't know how to use

### ISSUE THREAD

**Issue by Mystik01** [MrPotatoBobx/FetchCord#111]
# How you tried to install fetchcord
I used Pip to install.
**This can be AUR, Github, or pip.**

# Operating system
Windows 10 Pro
**Your OS goes here.**

# Other notes

**Other notes about install error/issue.**
'neofetch' is not recognized as an internal or external command,
operable program or batch file.
Unknown GPU, contact us on github to resolve this.
Unknown DE/WM, contact us on github to resolve this.
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact us on the GitHub page to resolve this.(keyerror)
Traceback (most recent call last):
  File "c:/Users/admin/AppData/Roaming/Python/Python38/site-packages/fetch_cord/__main__.py", line 1, in <module>
    from fetch_cord import run_rpc
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\fetch_cord\run_rpc.py", line 11, in <module>
    from fetch_cord.testing import gpuid, cpuappid, appid, desktopid, termappid, hostappid, shellid, moboid
ImportError: cannot import name 'moboid' from 'fetch_cord.testing' (C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\fetch_cord\testing.py)

I'm using Windows Terminal Preview. 
Also what command do i do o run it?

**Comment by BlivionIaG** [comment]
Hi, did you installed neofetch ? You can install it through scoop, we also support neofetch-win : ```pip install neofetch-win```

**Comment by Mystik01** [comment]
yes neofetch is already installed

**Comment by BlivionIaG** [comment]
Ok, so does it output something when you do neofetch command ?

**Comment by Mystik01** [comment]
What's the neofetch command? If I just type nefetch in the terminal it just gives me the 'is not recognized' thing.

**Comment by Mystik01** [comment]
might need to update my path

**Comment by Mystik01** [comment]
Just updated my path now I get my PC specs...

**Comment by Mystik01** [comment]
Now I run fetchcord it says connected however...
```
Unknown DE/WM, contact us on github to resolve this.
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Connecting
('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
RPC Connection Successful.
```

**Comment by Mystik01** [comment]
it works now however I do get the error above

**Comment by BlivionIaG** [comment]
If you give me your neofetch output i might be able to add missing infos,  but it's working i guess, we also have a discord if you want to ask more questions.

**Comment by Mystik01** [comment]
![image](https://user-images.githubusercontent.com/65687597/99882035-6a0b6880-2c15-11eb-9904-184ef342c156.png)

**Comment by Mystik01** [comment]
ok doesnt work on py 3.9 btw
