### ISSUE TITLE
Unknown icon issue for old celeron processor

### ISSUE THREAD

**Issue by MangyCat** [MrPotatoBobx/FetchCord#119]
# Debug info

**----out.py----

----DE/WM----

----GPU INFO----

gpuinfo: GPU: Intel(R) HD Graphics
gpuvendor: Intel(R)

----CPU INFO----

cpuvendor: Intel
cpumodel: Intel CPU
cpuinfo: CPU: Intel CPU G530 @ 2.40GHz
cpuline item 0: ['CPU: Intel(R) Celeron(R) CPU G530 @ 2.40GHz']
memline: Memory: 3.3GiB / 3.7GiB (89.76%)

----OS INFO----

sysosline: OS: Windows 10 Pro
sysosid: Windows10
diskline: Disk: C: 210.7GiB / 253.4GiB (83.16%)
Disk:D: 186.3GiB / 211.9GiB (87.93%)
Unknown GPU, contact us on github to resolve this.
Unknown DE/WM, contact us on github to resolve this.
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
unknown CPU, contact us on github to resolve this.(Keyerror)

----testing.py----
moboid: asus
moboline: Motherboard: ASUSTeK COMPUTER INC. (P8H61-M LX3 R2.0)

----GPU INFO----

gpuvendor: Intel(R)

----CPU INFO----

cpumodel: Intel CPU

Connecting
----run_rpc----

uptime in epoch: 1607105389.540314
cpuid: 741949889465942099
cpuappid: 742887089179197462
('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
RPC Connection Successful.
w_cycle 0**

**If you are unable to run FetchCord please run `neofetch --noart`(windows) or `neofetch -- stdout`(macos&linux)**

# Windows 10 Pro 64 bit

**I did pip install fetchcord neofetch-win**

# Unknown icon issue for old Intel CPU

**Your error or bug report goes in here.**

# I got a computer from 2012, with a old processor and it won't display it's icon the CPU is a Intel Celeron G530 2.4GHZ

** I am unable to upgrade my setup, sorry if it bothers you**
![Captu1re](https://user-images.githubusercontent.com/73955445/101404298-bf629d80-38d6-11eb-9614-329084541ca6.PNG)

**Comment by BlivionIaG** [comment]
Thanks, i'm supposing that it wont work with the new 2.7.0 version but can you try with it ?

**Comment by MangyCat** [comment]
> Thanks, i'm supposing that it wont work with the new 2.7.0 version but can you try with it ?

I am using python 3.9.0 I'm not very used to python 2

**Comment by BlivionIaG** [comment]
Oh sorry I didn't saw you reply, I was talking about fetchcord 2.7.0 ^^

**Comment by MrPotatoBobx** [comment]
going to close this issue, reopen if this problem still happens
