### ISSUE TITLE
Adding Garuda Linux OS

### ISSUE THREAD

**Issue by Ilovemyhous** [MrPotatoBobx/FetchCord#135]
# Debug info

**fetchcord --debug**
[KeyError]: 'Font:'[KeyError]: 'Font:'----run_rpc----

uptime in epoch: 1614692662.0
Unknown distro, contact us on github to resolve this.
cpuid: 742993278143692821
cpuappid: 740752899054895105
termappid: 741286819676553258
hostappid: 744326223412461630
1719 (pacman) 
----out.py----

----DE/WM----
deid: Plasma
wmid: KWin
wmline item 0: KWin 

----TERMINAL----

[KeyError]: 'Font:'
fontline: Font: N/A
termid: 741286819676553258
termline item 0: konsole 
[KeyError]: 'Theme:'
themeline: Theme: N/A

----HOST INFO----

hostline: 82B5 Lenovo Legion 5 15ARH05 
[KeyError]: 'Battery:'
[KeyError]: 'Battery:'
batteryline: Battery: N/A
resline: 1920x1080 @ 60.00Hz, 1920x1080 @ 120.21Hz 

----GPU INFO----

gpuinfo: GeForce GTX 1650 Ti/PCIe/SSE2
NVIDIA GeForce GTX 1650 Ti Mobile
gpuvendor: nvidiaamd

----CPU INFO----

cpuvendor: amd
cpumodel: Ryzen 7
cpuinfo: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.9GHz [40.0°on]
cpuline item 0: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.9GHz [40.0°on]
memline: 6965MiB / 15434MiB 

----OS INFO----

sysosline: Garuda x86_64 
Unknown distro, contact us on github to resolve this.
sysosid: 742993278143692821
diskline: /): 25G / 111G (23%) 
packagesline item 0: 1719 (pacman) 

----testing.py----
----DE/WM----

deid: Plasma
wmid: KWin

----TERMINAL/SHELL----

termid: 741286819676553258
shellid: fish

----HOST INFO----

hostid: 742887089179197462

----GPU INFO----

gpuvendor: nvidiaamd

----CPU INFO----

cpumodel: Ryzen 7

('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
Unknown distro, contact us on github to resolve this.
{}
cycle0 not in : True
try_connect(key="cycle0") on <pypresence.presence.Presence object at 0x7fe7bc181be0>
cycle 0
try_update(key="cycle0") on <pypresence.presence.Presence object at 0x7fe7bc181be0>
Unknown distro, contact us on github to resolve this.

**neofetch --stdout**
OS: Garuda x86_64 
Host: 82B5 Lenovo Legion 5 15ARH05 
Kernel: 5.11.2-128-tkg-bmq 
Uptime: 2 hours, 21 mins 
Packages: 1719 (pacman) 
Shell: /usr/bin/fish 3.1.2 
Resolution: 1920x1080 @ 60.00Hz, 1920x1080 @ 120.21Hz 
DE: Plasma 5.21.1 
WM: KWin 
Terminal: konsole 
Terminal Font: Fantasque Sans Mono 12 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.9GHz [39.0°on] 
GPU: AMD ATI 05:00.0 Renoir 
GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
Memory: 6933MiB / 15434MiB 
GPU Driver: NVIDIA 460.39 
Disk (/): 25G / 111G (23%) 
Battery0: 90% [Unknown] 

# Requested item

Hello!
Can you please add support for Garuda?
Thanks!

# Other notes

_None_

**Comment by BlivionIaG** [comment]
@Ilovemyhous Hello can you try with the new fetchcord version ? 
```pip3 install fetchcord --upgrade``` or ```pip install fetchcord --upgrade```

**Comment by Ilovemyhous** [comment]
Hello!
After a few issues installing it. It finally works.
Thanks for your work! ;)
![image](https://user-images.githubusercontent.com/50217071/112897277-b4c75080-90df-11eb-9df2-41278d07684c.png)
