### ISSUE TITLE
Add Xmonad to supported WM's

### ISSUE THREAD

**Issue by SimPilotAdamT** [MrPotatoBobx/FetchCord#140]
# Debug info

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[14:44:28] adam@Adam-Arch /home/adam  
> neofetch --stdout 
adam@Adam-Arch 
-------------- 
OS: Arch Linux x86_64 
Host: 20M50013UK ThinkPad L380 
Kernel: Linux 5.11.6-arch1-1 
Uptime: 15 mins 
Packages: 1930 (pacman) 
Shell: /usr/bin/fish 3.2.0-46-ga7df92e18 
Resolution: 1920x1080 @ 60.02Hz 
WM: xmonad 
Terminal: konsole 
Terminal Font: Ubuntu Mono 11 
CPU: Intel i5-8250U (4) @ 3.400GHz [51.0°C] 
CPU Usage: 16% 
GPU: Intel UHD Graphics 620 
Memory: 1.62GiB / 31.12GiB (5%) 
Disk (/): 49G / 290G (18%) 
Battery0: 78% [Discharging] 

[14:44:37] adam@Adam-Arch /home/adam  
> fetchcord --debug
[KeyError]: 'Font:'[KeyError]: 'Font:'----run_rpc----

uptime in epoch: 1615732162.0
cpuid: 740476198437650473
cpuappid: 741099939198926920
termappid: 741286819676553258
hostappid: 744326223412461630
1930 (pacman) 
----out.py----

----DE/WM----
[KeyError]: 'DE:'
deid: DE:
wmid: xmonad
wmline item 0: xmonad 

----TERMINAL----

[KeyError]: 'Font:'
fontline: Font: N/A
termid: 741286819676553258
termline item 0: konsole 
[KeyError]: 'Theme:'
themeline: Theme: N/A

----HOST INFO----

hostline: 20M50013UK ThinkPad L380 
[KeyError]: 'Battery:'
[KeyError]: 'Battery:'
batteryline: Battery: N/A
resline: 1920x1080 @ 60.02Hz 

----GPU INFO----

gpuinfo: Intel UHD Graphics 620
gpuvendor: intel

----CPU INFO----

cpuvendor: intel
cpumodel: Intel i5
cpuinfo: Intel i5-8250U (4) @ 3.400GHz [54.0°C]
cpuline item 0: Intel i5-8250U (4) @ 3.400GHz [54.0°C]
memline: 1.62GiB / 31.12GiB (5%) 

----OS INFO----

sysosline: Arch Linux x86_64 
sysosid: 740476198437650473
diskline: /): 49G / 290G (18%) 
packagesline item 0: 1930 (pacman) 

----testing.py----
----DE/WM----

[KeyError]: 'DE:'
deid: DE:
wmid: xmonad

----TERMINAL/SHELL----

termid: 741286819676553258
shellid: fish

----HOST INFO----

hostid: 742887089179197462

----GPU INFO----

gpuvendor: intel

----CPU INFO----

cpumodel: Intel i5

('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
{}
cycle0 not in : True
try_connect(key="cycle0") on <pypresence.presence.Presence object at 0x7fdcaf4de5e0>
[KeyError]: 'DE:'
Unknown DE/WM, contact us on github to resolve this.
cycle 0
[KeyError]: 'DE:'
try_update(key="cycle0") on <pypresence.presence.Presence object at 0x7fdcaf4de5e0>
appid: 740476198437650473
^CClosing connection.
[14:45:34] adam@Adam-Arch /home/adam  
> 

# Requested item
Xmonad

# Other notes

So that ppl like me can show off their tiling wm (lmao)

**Comment by BlivionIaG** [comment]
@SimPilotAdamT  
Hello can you try with the new fetchcord version ? 
```pip3 install fetchcord --upgrade``` or ```pip install fetchcord --upgrade```

**Comment by SimPilotAdamT** [comment]
@BlivionIaG Works. I will close this issue (shame that AUR installs don't work... maybe try to update the PKGBUILD?)

**Comment by BlivionIaG** [comment]
Hello, yes i saw that aur repo isn't working anymore, it's unofficial so I can't do anything, I'd like to see with the maintainer if we can add the testing branch, that way it'll be easy to know when it's not working.
