### ISSUE TITLE
It has no clue

### ISSUE THREAD

**Issue by g33kz4su** [MrPotatoBobx/FetchCord#145]
# Debug info

fetchcord --debug
mrgfy@arcolab 
------------- 
OS: ArcoLinux x86_64 
Kernel: 5.11.11-arch1-1 
Uptime: 2 hours, 7 mins 
Packages: 4139 (pacman), 1 (pkg), 19 (flatpak) 
Shell: fish 3.2.1 
Resolution: 1920x1080, 1920x1080 
DE: Xfce 4.16 
WM: Xfwm4 
WM Theme: AshOS-Dark 
Theme: Sweet-Dark [GTK2], deepin-dark [GTK3] 
Icons: BeautyLine [GTK2/3] 
Terminal: guake 
CPU: AMD Ryzen 3 2300X (4) @ 3.500GHz 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 7993MiB / 32033MiB 
Disk (/): 128G / 219G (62%)
[KeyError]: 'Font:'[KeyError]: 'Font:'[KeyError]: 'Host:'
----run_rpc----

uptime in epoch: 1617475819.0
cpuid: 745435867971321866
cpuappid: 741153175779803146
Unknown terminal, contact us on github to resolve this.
termappid: 745691250186911796
[KeyError]: 'Host:'
4139 (pacman), 1 (pkg), 19 (flatpak) 
----out.py----

----DE/WM----
deid: Xfce
wmid: Xfwm4
wmline item 0: Xfwm4 

----TERMINAL----

[KeyError]: 'Font:'
fontline: Font: N/A
Unknown terminal, contact us on github to resolve this.
termid: 745691250186911796
termline item 0: guake 
themeline: AshOS-Dark 
Sweet-Dark [GTK2], deepin-dark [GTK3] 
[KeyError]: 'Host:'

----GPU INFO----

gpuinfo: Radeon RX 570 Series
gpuvendor: amd

----CPU INFO----

cpuvendor: amd
cpumodel: Ryzen 3
cpuinfo: AMD Ryzen 3 2300X (4) @ 3.500GHz
cpuline item 0: AMD Ryzen 3 2300X (4) @ 3.500GHz
memline: 7993MiB / 32033MiB 

----OS INFO----

sysosline: ArcoLinux x86_64 
sysosid: 745435867971321866
diskline: /): 128G / 219G (62%)
packagesline item 0: 4139 (pacman), 1 (pkg), 19 (flatpak) 

----testing.py----
----DE/WM----

deid: Xfce
wmid: Xfwm4

----TERMINAL/SHELL----

Unknown terminal, contact us on github to resolve this.
termid: 745691250186911796
shellid: fish

----HOST INFO----

[KeyError]: 'Host:'
[KeyError]: 'Host:'
hostid: 742887089179197462

----GPU INFO----

gpuvendor: amd

----CPU INFO----

cpumodel: Ryzen 3

('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
Unknown terminal, contact us on github to resolve this.
[KeyError]: 'Host:'
Unknown motherboard, contact us on github to resolve this.
{}
cycle0 not in : True
try_connect(key="cycle0") on <pypresence.presence.Presence object at 0x7fec1a87b160>
cycle 0
try_update(key="cycle0") on <pypresence.presence.Presence object at 0x7fec1a87b160>
appid: 745435867971321866
{'cycle0': <pypresence.presence.Presence object at 0x7fec1a87b160>}
cycle1 not in : True
try_connect(key="cycle1") on <pypresence.presence.Presence object at 0x7fec1a87b280>
cycle 1
try_update(key="cycle1") on <pypresence.presence.Presence object at 0x7fec1a87b280>
appid: 741153175779803146
^CClosing connection.

![image](https://user-images.githubusercontent.com/76766272/113491260-4b9b6080-9484-11eb-8764-292b9cd93763.png)
what my neofetch outputs
![image](https://user-images.githubusercontent.com/76766272/113491296-8bfade80-9484-11eb-88cc-198ea171c4dd.png)

**Comment by BlivionIaG** [comment]
Hello, your custom neofetch config breaks it because it uses ">" as a separator, it should run fine without the neofetch config argument. It is planned to get rid of that limitation, though its not a priority.
