### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by watashiDepression** [MrPotatoBobx/FetchCord#147]
# How you tried to install fetchcord

Github

# Operating system

Windows 10

# Other notes

When I try to install fetchcord, it says to me that 'fetchcord' is not recognized as an internal or external command,
operable program or batch file.

**Comment by BlivionIaG** [comment]
Hello, it most probably doesn't work because  the path to the python script folder isn't added to your path environment variable.

**Comment by watashiDepression** [comment]
# From official site

**Comment by watashiDepression** [comment]
If i do python3 -m fetch_cord it shows me:

# C:\Users\gabri>python3 -m fetch_cord
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by watashiDepression** [comment]
I think that's because my Python version is not working well.
