### ISSUE TITLE
[Request] iPhone support

### ISSUE THREAD

**Issue by GingkathFox** [MrPotatoBobx/FetchCord#150]
# Debug info

`fetchcord --debug`:
```

Gingkas-IPhone-1:~# fetchcord --debug
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/fetch_cord/__main__.py", line 51, in main
    computer: Computer = Computer()
  File "/usr/lib/python3.8/site-packages/fetch_cord/computer/Computer.py", line 289, in __init__
    self.uptime = psutil.boot_time()
  File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2304, in boot_time
    return _psplatform.boot_time()
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1441, in boot_time
    raise RuntimeError(
RuntimeError: line 'btime' not found in /proc/stat
```
`neofetch --stdout`:
```

Gingkas-IPhone-1:~# neofetch --stdout
root@Gingkas-IPhone-1 
--------------------- 
OS: Alpine Linux v3.12 i686 
Kernel: 4.20.69-ish 
Uptime: 1 hour, 29 mins 
Packages: 149 (apk) 
Shell: ash 
Memory: 3652MiB / 3801MiB
```

# Requested item
I'm bored so why not add iPhone support? Just using this as a reminder for myself to try and implement when I get on my Mac. The current issue is boottime, I think that would be interchangeable with uptime which is in `/proc/uptime`.

**Comment by GingkathFox** [comment]
@MrPotatoBobx could you assign this to me?

**Comment by GingkathFox** [comment]
So i got it working, except apparently discord mobile doesnt have rpc support? im sad now

**Comment by MrPotatoBobx** [comment]
that was what i was about to say, unfortunatley  there will be no mobile support

**Comment by luni-moon** [comment]
> # Debug info
> 
> `fetchcord --debug`:
> 
> ```
> 
> Gingkas-IPhone-1:~# fetchcord --debug
> Traceback (most recent call last):
>   File "/usr/bin/fetchcord", line 8, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.8/site-packages/fetch_cord/__main__.py", line 51, in main
>     computer: Computer = Computer()
>   File "/usr/lib/python3.8/site-packages/fetch_cord/computer/Computer.py", line 289, in __init__
>     self.uptime = psutil.boot_time()
>   File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2304, in boot_time
>     return _psplatform.boot_time()
>   File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1441, in boot_time
>     raise RuntimeError(
> RuntimeError: line 'btime' not found in /proc/stat
> ```
> 
> `neofetch --stdout`:
> 
> ```
> 
> Gingkas-IPhone-1:~# neofetch --stdout
> root@Gingkas-IPhone-1 
> --------------------- 
> OS: Alpine Linux v3.12 i686 
> Kernel: 4.20.69-ish 
> Uptime: 1 hour, 29 mins 
> Packages: 149 (apk) 
> Shell: ash 
> Memory: 3652MiB / 3801MiB
> ```
> 
> # Requested item
> 
> I'm bored so why not add iPhone support? Just using this as a reminder for myself to try and implement when I get on my Mac. The current issue is boottime, I think that would be interchangeable with uptime which is in `/proc/uptime`.

Weird thing, I got `fetchcord -h` to work, using ISH, so there may be some hope :)

**Comment by 0xf0xx0** [comment]
> > # Debug info
> 
> > 
> 
> > `fetchcord --debug`:
> 
> > 
> 
> > ```
> 
> > 
> 
> > Gingkas-IPhone-1:~# fetchcord --debug
> 
> > Traceback (most recent call last):
> 
> >   File "/usr/bin/fetchcord", line 8, in <module>
> 
> >     sys.exit(main())
> 
> >   File "/usr/lib/python3.8/site-packages/fetch_cord/__main__.py", line 51, in main
> 
> >     computer: Computer = Computer()
> 
> >   File "/usr/lib/python3.8/site-packages/fetch_cord/computer/Computer.py", line 289, in __init__
> 
> >     self.uptime = psutil.boot_time()
> 
> >   File "/usr/lib/python3.8/site-packages/psutil/__init__.py", line 2304, in boot_time
> 
> >     return _psplatform.boot_time()
> 
> >   File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 1441, in boot_time
> 
> >     raise RuntimeError(
> 
> > RuntimeError: line 'btime' not found in /proc/stat
> 
> > ```
> 
> > 
> 
> > `neofetch --stdout`:
> 
> > 
> 
> > ```
> 
> > 
> 
> > Gingkas-IPhone-1:~# neofetch --stdout
> 
> > root@Gingkas-IPhone-1 
> 
> > --------------------- 
> 
> > OS: Alpine Linux v3.12 i686 
> 
> > Kernel: 4.20.69-ish 
> 
> > Uptime: 1 hour, 29 mins 
> 
> > Packages: 149 (apk) 
> 
> > Shell: ash 
> 
> > Memory: 3652MiB / 3801MiB
> 
> > ```
> 
> > 
> 
> > # Requested item
> 
> > 
> 
> > I'm bored so why not add iPhone support? Just using this as a reminder for myself to try and implement when I get on my Mac. The current issue is boottime, I think that would be interchangeable with uptime which is in `/proc/uptime`.
> 
> 
> 
> Weird thing, I got `fetchcord -h` to work, using ISH, so there may be some hope :)
> 
> 

Discord iOS doesn't have RPC.
