### ISSUE TITLE
Add Artix and EndeavourOS

### ISSUE THREAD

**Issue by thederpyllamas** [MrPotatoBobx/FetchCord#2]

**Comment by MrPotatoBobx** [comment]
Okay, ill work on that!

**Comment by MrPotatoBobx** [comment]
can you send the output when running `run -rpc` on eandevour?

**Comment by MrPotatoBobx** [comment]
artix was added under `arch` becuase its arch without systemd and doesnt really make a diffrence(if you hover over the arch logo it will show artix)

**Comment by MrPotatoBobx** [comment]
done
