### ISSUE TITLE
Update readme: Clarify what "the discord script" is

### ISSUE THREAD

**Issue by Adora16** [MrPotatoBobx/FetchCord#27]
I have the scripts for both Discord and FetchCord in my path; however, FetchCord is not run when I start Discord. Does the readme refer to a different Discord script?

**Comment by Hyper-KVM** [comment]
it's referring to the one in the repo, you can just replace the one you have with that one.

**Comment by lorddickfist** [comment]
I +1 this, I don't know how to set this up at all from reading the readme.

**Comment by JamiKettunen** [comment]
This script is now removed in favor of making `fetchcord` a daemon and giving the user the freedom to launch it in whichever way they prefer (like on boot for example). There is a working systemd unit present in the repo which you can see the README instructions for in case you want to test it.

**Comment by lorddickfist** [comment]
> This script is now removed in favor of making `fetchcord` a daemon and giving the user the freedom to launch it in whichever way they prefer (like on boot for example). There is a working systemd unit present in the repo which you can see the README instructions for in case you want to test it.

Will check it out when I get home,  much appreciated.
