### ISSUE TITLE
Issue with terminal in LM20(Cinnamon)

### ISSUE THREAD

**Issue by hikiyaaa** [MrPotatoBobx/FetchCord#28]
After multiple issues involving separate logical partitions(one for Home and one for Root), I have finally been able to get a result from typing `Fetchord` into gnome-terminal. However, after the following output:
`Connecting
RPC connection successful.
`
The terminal process does not run in the background. I cannot find a way to 'disown' the 'job', so in order to keep the program running I always need to have a terminal window open. I've tried to work around this by switching to a different desktop, but I don't think that it's the best solution. Is fetchcord supposed to act like this, or is it a problem with my system? I have followed the installation and startup instruction just as shown on the homepage, besides reinstalling 10395028674030847539484 times since my system is rather problematic due to my partitioning system. Otherwise, fetchcord works perfectly. I do have 2 requests but I'm not going to put them here as I don't know how difficult it will be to heed them.

**Comment by hikiyaaa** [comment]
ok that was nerdy

**Comment by Hyper-KVM** [comment]
for the other 2 requests, just make another issue or 2 whatever and we'll see what we can do about them.

**Comment by hikiyaaa** [comment]
One is already being addressed.

**Comment by MrPotatoBobx** [comment]
can you try againn?

**Comment by MrPotatoBobx** [comment]
This issue will be closed in 1 day.
