### ISSUE TITLE
Having trouble with running Fetchcord on MacOS 10.15.5

### ISSUE THREAD

**Issue by WarpWing** [MrPotatoBobx/FetchCord#29]
Hi! I have a error when running this on my terminal. I did pip3 install fetchcord and attempted to run fetchcord

This was the output
![Screen Shot 2020-08-15 at 12 02 31 AM](https://user-images.githubusercontent.com/28925758/90304921-d5150880-de8a-11ea-878e-44525b6b57d6.png)

**Comment by WarpWing** [comment]
Hey so. Waking up this morning, I saw that Hyper(thx Hyper) fixed the typo in testing.py so I fixed it on my side too. However, I still have trouble running fetchcord. Here is the error

![Screen Shot 2020-08-15 at 9 28 28 AM](https://user-images.githubusercontent.com/28925758/90313358-e46f7280-ded9-11ea-85d9-d883d742b3cd.png)

**Comment by Hyper-KVM** [comment]
I had to fix a bunch of other stuff too, @MrPotatoBobx updated the pip package though so try again and if another error happens post here and I'll fix it.

**Comment by WarpWing** [comment]
Thx for the support. I actually encountered another error when attempting to run fetchcord (even after manuelly fixing the typo error) 

![Screen Shot 2020-08-15 at 11 41 46 AM](https://user-images.githubusercontent.com/28925758/90315820-6c5e7800-deec-11ea-8811-ee0a32e6cd01.png)

**Comment by Hyper-KVM** [comment]
yeah I fixed that one too.

**Comment by WarpWing** [comment]
Alrighty, let me do pip3 uninstall and reinstall! I'll update you if it works :D

**Comment by WarpWing** [comment]
So I attempted to reinstall via pip and I'm getting the same errors that I did this morning as well as those that were fixed according to you. Do I have to build it manually or something?

**Comment by Hyper-KVM** [comment]
Huh, pretty sure I saw him update the pip package... welp, short of waiting for an update, yeah you can build right from master.

**Comment by Hyper-KVM** [comment]
Hi, try the master version, it should work as expected now

**Comment by WarpWing** [comment]
If I could ask, how do I build it from master?

**Comment by Hyper-KVM** [comment]
use `python3 setup.py install --root='/path/to/install/to'`

**Comment by WarpWing** [comment]
thx :D I'll let you know how it goes

**Comment by WarpWing** [comment]
![Screen Shot 2020-08-15 at 4 10 20 PM](https://user-images.githubusercontent.com/28925758/90320793-0c7ac800-df12-11ea-89ee-65528a640d68.png)

Thanks for the help <3
