### ISSUE TITLE
Request; Systemd support

### ISSUE THREAD

**Issue by alanxyz** [MrPotatoBobx/FetchCord#32]
Would love systemd support, so this is running 24/7 on my machine.

**Comment by JamiKettunen** [comment]
@alanxyz Could you check out the latest master and README instructions? I've written a proper unit file which should work for you as well.

Only To-Do would be to install the service file from `setup.py` but I'm yet to find a sane method to do so without unnecessarily installing the unit also for non-sysd users, or making said `setup.py` script unnecessarily complicated :/

**Comment by alanxyz** [comment]
Hello, thank you for the quick response! The `setup.py` file installs fetchcord fine, however I am having an issue with the service. 
`Aug 16 22:49:16 alnux fetchcord[89735]:   File "/home/alan/.local/bin/fetchcord", line 5, in <module>
Aug 16 22:49:16 alnux fetchcord[89735]:     from fetch_cord.run_rpc import main
Aug 16 22:49:16 alnux fetchcord[89735]:   File "/home/alan/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 8, in <module>
Aug 16 22:49:16 alnux fetchcord[89735]:     from fetch_cord.testing import uptime, gpuid, desktopid, appid, cpuappid, termappid
Aug 16 22:49:16 alnux fetchcord[89735]:   File "/home/alan/.local/lib/python3.8/site-packages/fetch_cord/testing.py", line 5, in <module>
Aug 16 22:49:16 alnux fetchcord[89735]:     from fetch_cord.out import wmid, deid, termid, shellid, cpumodel, cpuvendor, gpuvendor, sysosid
Aug 16 22:49:16 alnux fetchcord[89735]:   File "/home/alan/.local/lib/python3.8/site-packages/fetch_cord/out.py", line 212, in <module>
Aug 16 22:49:16 alnux fetchcord[89735]:     termid = termline[0].split()[1]
Aug 16 22:49:16 alnux fetchcord[89735]: IndexError: list index out of range
Aug 16 22:49:16 alnux systemd[479]: fetchcord.service: Succeeded.
`
This is what I get when I look at the status of the service. Any help would be appreciated!

**Comment by JamiKettunen** [comment]
That issue looks to be out of the scope of the service file as it's an issue in the script itself (index out of range error); did you try launching the script using just `fetchcord` from a terminal to confirm it also happens there? `master` probably was broken again since I tested this myself yesterday, so try updating it once more now (commit `196c009778f0afa1ec035e89a32eda2f9ee86699` *should* be "stable" as it's the 2.5 release).

**Comment by JamiKettunen** [comment]
It seems the unit is flawed as well though, I never tested if it worked when you reboot aaand ofc it's broken lol
```
$ journalctl --user -u fetchcord -b
-- Logs begin at Tue 2019-12-17 21:17:48 EET, end at Tue 2020-08-18 14:38:39 EEST. --
systemd[1494]: Started Display OS info as Discord Rich Presence.
fetchcord[1507]: setting custom time 20
fetchcord[1507]: Unknown Host, contact us on github to resolve this.(Keyerror)
fetchcord[1507]: Unsupported Wm contact me on github to resolve this.(Keyerror)
fetchcord[1507]: Unknown GPU, contact me on github to resolve this.(Keyerror)
fetchcord[1507]: Connecting
fetchcord[1507]: RPC connection successful.
fetchcord[1507]: Traceback (most recent call last):
fetchcord[1507]:   File "/home/deathmist/.local/bin/fetchcord", line 33, in <module>
fetchcord[1507]:     sys.exit(load_entry_point('FetchCord==2.4', 'console_scripts', 'fetchcord')())
fetchcord[1507]:   File "/home/deathmist/.local/lib/python3.8/site-packages/FetchCord-2.4-py3.8.egg/fetch_cord/run_rpc.py", line 40, in main
fetchcord[1507]:     loonix()
fetchcord[1507]:   File "/home/deathmist/.local/lib/python3.8/site-packages/FetchCord-2.4-py3.8.egg/fetch_cord/run_rpc.py", line 272, in loonix
fetchcord[1507]:     cycle0()
fetchcord[1507]:   File "/home/deathmist/.local/lib/python3.8/site-packages/FetchCord-2.4-py3.8.egg/fetch_cord/run_rpc.py", line 117, in cycle0
fetchcord[1507]:     rpc_tryconnect()
fetchcord[1507]:   File "/home/deathmist/.local/lib/python3.8/site-packages/FetchCord-2.4-py3.8.egg/fetch_cord/run_rpc.py", line 53, in rpc_tryconnect
fetchcord[1507]:     RPC.connect()
fetchcord[1507]:   File "/home/deathmist/.local/lib/python3.8/site-packages/pypresence/presence.py", line 41, in connect
fetchcord[1507]:     self.loop.run_until_complete(self.handshake())
fetchcord[1507]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
fetchcord[1507]:     return future.result()
fetchcord[1507]:   File "/home/deathmist/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 121, in handshake
fetchcord[1507]:     self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
fetchcord[1507]:   File "/usr/lib/python3.8/asyncio/streams.py", line 111, in open_unix_connection
fetchcord[1507]:     transport, _ = await loop.create_unix_connection(
fetchcord[1507]:   File "/usr/lib/python3.8/asyncio/unix_events.py", line 244, in create_unix_connection
fetchcord[1507]:     await self.sock_connect(sock, path)
fetchcord[1507]:   File "/usr/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
fetchcord[1507]:     return await fut
fetchcord[1507]:   File "/usr/lib/python3.8/asyncio/selector_events.py", line 499, in _sock_connect
fetchcord[1507]:     sock.connect(address)
fetchcord[1507]: FileNotFoundError: [Errno 2] No such file or directory
systemd[1494]: fetchcord.service: Succeeded.
```
It looks to start up way before you've reached the desktop, so it would have to only launch after a DE/WM is running somehow...
For now though `systemctl --user start fetchcord` will at least work, I'll look into this later if no one else is interested in fixing it.

**Comment by alanxyz** [comment]
Starting it once in the DE/WM has fixed my issue! Thank you! I believe the error was caused due to me messing around with the `PIP` and `AUR` version, as the `AUR` version (which was launched when I did the `fetchcord` command, unlike the service which called the `PIP` version, hopefully that made sense.)

**Comment by MrPotatoBobx** [comment]
is the problem fixed?

**Comment by alanxyz** [comment]
Yup.

**Comment by Hyper-KVM** [comment]
closing since problem is fixed.
