### ISSUE TITLE
fetchcord: command not found

### ISSUE THREAD

**Issue by A-Random-Lantern** [MrPotatoBobx/FetchCord#33]
USER@PC:~$ fetchcord
fetchcord: command not found

It is installed in .local/bin

Pop!_OS 20.04
was installed with "pip3 install fetchcord"

**Comment by Hyper-KVM** [comment]
~/.local is not in PATH

**Comment by A-Random-Lantern** [comment]
How can I fix this then? I don't know how to use python that much.
