### ISSUE TITLE
Request, Adding Tmux Logo

### ISSUE THREAD

**Issue by JadenJSJ** [MrPotatoBobx/FetchCord#35]
Please add functality for tmux
Logo that i thought will fit
https://d2eip9sf3oo6c2.cloudfront.net/tags/images/000/001/048/square_480/tmux.png
JSJ_15#8889

**Comment by Hyper-KVM** [comment]
The problem with tmux is it doesn't show up on neofetch, so you'll have to use the --terminal flag to have it show up.

**Comment by Hyper-KVM** [comment]
added in master
