### ISSUE TITLE
Add windows

### ISSUE THREAD

**Issue by FJduFou** [MrPotatoBobx/FetchCord#4]
Can you add Windows:
The Windows logo of the version used in large, for example Windows10 / 8.1 / 8/7 ect ...
And in small if it is a VM (are name if you have it: VirtualBox ...) or a real PC and its brand / reference, for example ASUS Vivobook X411UA?
That's it that's all ;)

**Comment by MrPotatoBobx** [comment]
yea sure, ill try to get that working, its just a bit harder  because most of the info in linux/macos is gathered by unix commands

**Comment by Hyper-KVM** [comment]
actually, that should work now too, since we now pull straight from neofetch

**Comment by Hyper-KVM** [comment]
Windows should work on master now, needs a pip update but I'm not certain it's 100% stable.

**Comment by MrPotatoBobx** [comment]
windows now works, pip update soon :+1:
