### ISSUE TITLE
Issue: Gentoo shows up as "unknown"

### ISSUE THREAD

**Issue by MFHKiwi** [MrPotatoBobx/FetchCord#40]
This is the same issue that I described with urxvt, except it suddenly happened with the distro.

**Comment by Hyper-KVM** [comment]
Can you give a --debug log please.

**Comment by Hyper-KVM** [comment]
![2020-08-17_18_36_54_%N](https://user-images.githubusercontent.com/35402073/90451070-05da8500-e0b9-11ea-9a68-6d851e5682ac.png)
works for me

**Comment by MFHKiwi** [comment]
`['Font', 'Mono']
out
deid: Xfce
termfontline: Font Mono
amdgpurenderlist: ['GPU: AMD Radeon RX 5700 XT ']
amdgpurender: GPU: AMD Radeon RX 5700 XT 
intelgpuline: []
sysosline: ['OS: Gentoo/Linux x86_64 ']
gpuinfo: GPU: AMD Radeon RX 5700 XT 
gpuvendor: AMD
nvidiagpuline: []
cpuvendor: Intel
cpumodel: Intel i3
cpuline item 0: CPU: Intel i3-8100 (4) @ 3.600GHz 
wmid: Xfwm4
termid: urxvt
termline item 0: Terminal: urxvt 
packagesline item 0: Packages: 817 (emerge) 
sysosid: Gentoo/Linux
sysosline item 0: OS: Gentoo/Linux x86_64 
wmline item 0: WM: Xfwm4 
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact me on the GitHub page to resolve this.(keyerror)
testing
deid: Xfce
wmid: Xfwm4
termid: urxvt
shellid: zsh
hostid: 
cpumodel: Intel i3
gpuvendor: AMD
Connecting
RPC connection successful.
run-rpc
1597722462.0
742887089179197462
amd
Packages: 817 (emerge) 
cycle 0
appid: 742887089179197462`
I assume that you mean this.

**Comment by MFHKiwi** [comment]
`['Font', 'Mono']
out
deid: Xfce
termfontline: Font Mono
amdgpurenderlist: ['GPU: AMD Radeon RX 5700 XT ']
amdgpurender: GPU: AMD Radeon RX 5700 XT 
intelgpuline: []
sysosline: ['OS: Gentoo/Linux x86_64 ']
gpuinfo: GPU: AMD Radeon RX 5700 XT 
gpuvendor: AMD
nvidiagpuline: []
cpuvendor: Intel
cpumodel: Intel i3
cpuline item 0: CPU: Intel i3-8100 (4) @ 3.600GHz 
wmid: Xfwm4
termid: urxvt
termline item 0: Terminal: urxvt 
packagesline item 0: Packages: 817 (emerge) 
sysosid: Gentoo/Linux
sysosline item 0: OS: Gentoo/Linux x86_64 
wmline item 0: WM: Xfwm4 
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact me on the GitHub page to resolve this.(keyerror)
testing
deid: Xfce
wmid: Xfwm4
termid: urxvt
shellid: zsh
hostid: 
cpumodel: Intel i3
gpuvendor: AMD
Connecting
RPC connection successful.
run-rpc
1597722462.0
742887089179197462
amd
Packages: 817 (emerge)`

I assume that you mean this.

**Comment by Hyper-KVM** [comment]
ah, the real Gentoo OS: line in neofetch is Gentoo/Linux, not Gentoo, anyways, fixed in commit: b1f3c20d616f4499928b570b85e9baff28422814 so closing.
