### ISSUE TITLE
Add Funtoo (Gentoo fork) support or at least support choosing distro in an arguement

### ISSUE THREAD

**Issue by SAKO4444GODZ** [MrPotatoBobx/FetchCord#44]
Hello, it seems that this program doesn't detect Funtoo as Gentoo, can you do a similar thing to [https://github.com/MrPotatoBobx/FetchCord/issues/2#issuecomment-669504792](url)
Below is my terminal output
`sako@stalin-sodium ~ $ fetchcord 
['Mono', '11']
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact me on the GitHub page to resolve this.(keyerror)
Connecting
RPC connection successful.
^CClosing connection.
sako@stalin-sodium ~ $ `

**Comment by Hyper-KVM** [comment]
Can you give --debug log please.

**Comment by SAKO4444GODZ** [comment]
`sako@stalin-sodium ~ $ fetchcord --debug
laptop: True
['Mono', '11']
out
deid: KDE
termfontline: Mono 11
amdgpurenderlist: []
intelgpuline: []
sysosline: ['OS: Funtoo Linux 1.4 x86_64 ']
gpuinfo: GPU: NVIDIA GeForce GTX 1080 
gpuvendor: NVIDIA
nvidiagpuline: ['GPU: NVIDIA GeForce GTX 1080 ']
cpuvendor: Intel
cpumodel: Intel i5
cpuline item 0: CPU: Intel i5-8600 (6) @ 4.300GHz 
wmid: KWin
termid: konsole
termline item 0: Terminal: konsole 
packagesline item 0: Packages: 1551 (emerge), 18 (flatpak) 
sysosid: Funtoo
sysosline item 0: OS: Funtoo Linux 1.4 x86_64 
wmline item 0: WM: KWin 
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact me on the GitHub page to resolve this.(keyerror)
testing
deid: KDE
wmid: KWin
termid: konsole
shellid: bash
hostid: 
cpumodel: Intel i5
gpuvendor: NVIDIA
Connecting
RPC connection successful.
run-rpc
1597759171.0
742887089179197462
nvidia
Packages: 1551 (emerge), 18 (flatpak) 
cycle 0
appid: 742887089179197462
^CClosing connection.
sako@stalin-sodium ~ $`

**Comment by SAKO4444GODZ** [comment]
> `laptop: True`
this is on a desktop, not a laptop

**Comment by Hyper-KVM** [comment]
added, also having that say true for laptop is a bug, please make another issue so we can figure that out because that is unintended to occur.
