### ISSUE TITLE
Debug log claims that my desktop is a laptop

### ISSUE THREAD

**Issue by SAKO4444GODZ** [MrPotatoBobx/FetchCord#49]
`sako@stalin-sodium ~ $ fetchcord --debug
laptop: True
['Mono', '11']
out
deid: KDE
termfontline: Mono 11
amdgpurenderlist: []
intelgpuline: []
sysosline: ['OS: Funtoo Linux 1.4 x86_64 ']
gpuinfo: GPU: NVIDIA GeForce GTX 1080 
gpuvendor: NVIDIA
nvidiagpuline: ['GPU: NVIDIA GeForce GTX 1080 ']
cpuvendor: Intel
cpumodel: Intel i5
cpuline item 0: CPU: Intel i5-8600 (6) @ 4.300GHz 
wmid: KWin
termid: konsole
termline item 0: Terminal: konsole 
packagesline item 0: Packages: 1551 (emerge), 18 (flatpak) 
sysosid: Funtoo
sysosline item 0: OS: Funtoo Linux 1.4 x86_64 
wmline item 0: WM: KWin 
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact me on the GitHub page to resolve this.(keyerror)
testing
deid: KDE
wmid: KWin
termid: konsole
shellid: bash
hostid: 
cpumodel: Intel i5
gpuvendor: NVIDIA
Connecting
RPC connection successful.
run-rpc
1597759171.0
742887089179197462
nvidia
Packages: 1551 (emerge), 18 (flatpak) 
cycle 0
appid: 742887089179197462`

**Comment by Hyper-KVM** [comment]
can you run this: `cat /sys/module/battery`

**Comment by Hyper-KVM** [comment]
commit da5c122eae7f4576abff8ac5669dd7e3bbe32b33 should fix this, either wait for next stable release or try master to see if it works correctly.

**Comment by Hyper-KVM** [comment]
This is confirmed fixed, closing the issue.
