### ISSUE TITLE
how can i only show my os info?

### ISSUE THREAD

**Issue by itayalush1** [MrPotatoBobx/FetchCord#57]
i would like to have only my os info shown.
currently it shows other things in a cycle and i want just the os info, how would i go about doing this?
thanks for making this app.

**Comment by Hyper-KVM** [comment]
https://github.com/MrPotatoBobx/FetchCord#arguments

**Comment by itayalush1** [comment]
> https://github.com/MrPotatoBobx/FetchCord#arguments

this doesnt work for me

**Comment by Hyper-KVM** [comment]
What do you mean it doesn't work for you?

**Comment by itayalush1** [comment]
I am using this on i3 gaps, so to always run this I added it to my config file.
To the line that always runs this I added these arguments, and nothing changed. It stays the same

**Comment by Hyper-KVM** [comment]
what arguments?

**Comment by itayalush1** [comment]
I got it from the aur.
I wrote
Exec_always fetchcord --nohardware --nohost
(Exec_always is used to have fetchcord always running)

**Comment by Hyper-KVM** [comment]
do the arguments work if executed in a shell?

**Comment by MrPotatoBobx** [comment]
will close in 1 day.

**Comment by itayalush1** [comment]
sorry i took long to answer i had some issues...
the pip version doesnt make a diffrence.
