### ISSUE TITLE
Crashes on Ubuntu 20.10 Alphas

### ISSUE THREAD

**Issue by bittin** [MrPotatoBobx/FetchCord#76]
Hello!

Heard about this project in this weeks Linux Unplugged, but it does crash on my system, is there any log files or such that could be to any help for you?

**Comment by bittin** [comment]
It worked with gnome-terminal but not stterm: https://st.suckless.org/

**Comment by Hyper-KVM** [comment]
Odd, I have no problems using st. Can you provide --debug log please?

**Comment by MrPotatoBobx** [comment]
please.......

**Comment by BlivionIaG** [comment]
well since we don't have any feedback, i'm closing it
