### ISSUE TITLE
RX 5700 XT only shows up as "AMD Radeon RX"

### ISSUE THREAD

**Issue by MFHKiwi** [MrPotatoBobx/FetchCord#8]
My RX 5700 XT only shows up as "AMD Radeon RX", with no further details. Would be really sick if this could be fixed.

**Comment by Hyper-KVM** [comment]
should be fixed now

**Comment by MrPotatoBobx** [comment]
try again

**Comment by MrPotatoBobx** [comment]
will close both your issues in a day.
