### ISSUE TITLE
Unknown Host

### ISSUE THREAD

**Issue by Mintydaisy** [MrPotatoBobx/FetchCord#81]
I have a Gigabyte b450 Motherboard, system is built myself. I do not know if it is, an issue because it is a self built system. If so, maybe adding gigabyte motherboards instead of just saying, "unknown"

**Comment by MrPotatoBobx** [comment]
What operating system? and please send the debug log.

**Comment by Mintydaisy** [comment]
Ubuntu 20.04

----out.py----

----DE/WM----
deid: GNOME
wmid: Mutter
wmline item 0: WM: Mutter 

----TERMINAL----

termfontline: Font: N/A
termid: gnome-terminal
termline item 0: Terminal: gnome-terminal 
themeline: ['WM Theme: Adwaita ', 'Theme: Yaru-dark [GTK2/3] ']

----GPU INFO----

amdgpurenderlist: ['GPU: Radeon RX 580 Series ']
amdgpurender: GPU: Radeon RX 580 Series 
nvidiagpuline: []
intelgpuline: []
gpuinfo: GPU: Radeon RX 580 Series 
gpuvendor: AMD

----CPU INFO----

cpuvendor: AMD
cpumodel: Ryzen 5
cpuline item 0: CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz [33.5°C] 
memline: ['Memory: 8049MiB / 32107MiB']

----OS INFO----

sysosline: ['OS: Ubuntu 20.04.1 LTS x86_64 ']
sysosid: Ubuntu
packagesline item 0: Packages: 1722 (dpkg), 7 (snap) 
Unknown Host, contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: GNOME
wmid: Mutter

----TERMINAL/SHELL----

termid: gnome-terminal
shellid: bash

----HOST INFO----

hostid: 

----GPU INFO----

gpuvendor: AMD

----CPU INFO----

cpumodel: Ryzen 5

Connecting
----run_rpc----

uptime in epoch: 1598394341.0
cpuid: 740434138036699178
cpuappid: 741152732756312125
termappid: 741328861115056160
hostappid: 742887089179197462
Packages: 1722 (dpkg), 7 (snap) 
RPC Connection Successful.
cycle 0
appid: 740434138036699178

**Comment by cheesits456** [comment]
I'm also running a b450 motherboard (MSI Bazooka b450m to be precise) and mine also says:

> "Unknown Host, contact us on github to resolve this"

Saw this issue, and since mine is similar, I figured I'd just piggyback off this one rather than opening a new one

## Debug info

```
laptop: False
----out.py----

----DE/WM----
deid: Plasma
wmid: Compiz
wmline item 0: WM: Compiz 

----TERMINAL----

fontline: Terminal Font: N/A
Font: N/A
termid: konsole
termline item 0: Terminal: konsole 
themeline: WM Theme: Adwaita 
Theme: Flat-Remix-Blue-Dark [Plasma], Flat-Remix-GTK-Blue-Dark-Solid [GTK2/3] 

----HOST INFO----

hostline: ['Host: MS-7A38 5.0 ']

----GPU INFO----

gpuinfo: GPU: NVIDIA GeForce GTX 970 [55°C]
gpuvendor: NVIDIA

----CPU INFO----

cpuvendor: AMD
cpumodel: Ryzen 5
cpuinfo: CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz
cpuline item 0: CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz 
memline: Memory: 11188MiB / 32129MiB 

----OS INFO----

sysosline: ['OS: Arch Linux x86_64 ']
sysosid: Arch
packagesline item 0: Packages: 1622 (pacman), 4 (flatpak), 2 (snap) 
Unknown Host, contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: Plasma
wmid: Compiz

----TERMINAL/SHELL----

termid: konsole
shellid: bash

----HOST INFO----

hostid: MS-A

----GPU INFO----

gpuvendor: NVIDIA

----CPU INFO----

cpumodel: Ryzen 5
```

### Operating system & way of installation

Arch Linux, installed from AUR

### Other notes

MSi Bazooka b450m motherboard

**Comment by MrPotatoBobx** [comment]
i recommend installing from pip, please try fetchcord 2.7
