### ISSUE TITLE
Hostline is not defined & unknown motherboard

### ISSUE THREAD

**Issue by BennoMP** [MrPotatoBobx/FetchCord#87]
I have a Lenovo G50-70 (model 80DY), which has a Lenovo Lancer 5A2 motherboard according to neofetch.
I'm using Windows 10 build 19041.450 (aka 2004) and Python 3.7, 3.7.9 and 3.8.5 (I did run from the 3.7 folder all the time).
the errors I'm getting:
C:\Windows\system32>fetchcord
Unknown Motherboard, contact us on github to resolve this.(Keyerror)
Connecting
Traceback (most recent call last):
  File "c:\users\benno\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\benno\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\benno\AppData\Local\Programs\Python\Python37\Scripts\fetchcord.exe\__main__.py", line 7, in <module>
  File "c:\users\benno\appdata\local\programs\python\python37\lib\site-packages\fetch_cord\run_rpc.py", line 29, in main
    if not hostline and args.nodistro and args.noshell and args.nohardware:
NameError: name 'hostline' is not defined

**Comment by BennoMP** [comment]
I'd like to add that the bold "main" does have the double _ on both sides

**Comment by BlivionIaG** [comment]
Hi, can you give run with fetchcord --debug and give the results ? 
If possible the neofetch dump (```neofetch --noart``` if you are using neofetch-win, ```neofetch --stdout``` if its neofetch installed with scoop).
If  you are using neofetch-win do you have the latest version ? (1.1.1)
How did you installed fetchcord (pip or the git repo) ?

**Comment by BennoMP** [comment]
C:\Windows\system32>fetchcord --debug
----out.py----

----DE/WM----

----GPU INFO----

gpuinfo:
GPU: Intel(R) HD Graphics Family
gpuvendor: AMDIntel

----CPU INFO----

cpuvendor: Intel
cpumodel: Intel i5
cpuinfo: CPU: Intel i5-4210U CPU @ 1.70GHz
cpuline item 0: CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
memline: Memory: 5.5GiB / 7.9GiB (70.09%)

----OS INFO----

sysosline: ['OS: Windows 10 Pro']
sysosid: Windows10
diskline: Disk: C: 68.4GiB / 232.3GiB (29.45%)
Disk: D: 46.2GiB / 232.9GiB (19.86%)
Unknown Motherboard, contact us on github to resolve this.(Keyerror)

----testing.py----
moboid: unknown
moboline: ['Motherboard: LENOVO (Lancer 5A2)']

----GPU INFO----

gpuvendor: AMDIntel

----CPU INFO----

cpumodel: Intel i5

Connecting
Traceback (most recent call last):
  File "d:\software\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\software\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Software\Python\Python38\Scripts\fetchcord.exe\__main__.py", line 7, in <module>
  File "d:\software\python\python38\lib\site-packages\fetch_cord\run_rpc.py", line 29, in main
    if not hostline and args.nodistro and args.noshell and args.nohardware:
NameError: name 'hostline' is not defined

---

C:\Windows\system32>neofetch --noart
benno@BMP-Lenovo
----------------
OS: Windows 10 Pro
Uptime: 5 days, 4 hours, 14 minutes and 3 seconds
Local IP: 192.168.0.109
Motherboard: LENOVO (Lancer 5A2)
CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
GPU: Intel(R) HD Graphics Family
     AMD Radeon R5 M230
Memory: 5.4GiB / 7.9GiB (68.97%)
Disk: C: 68.4GiB / 232.3GiB (29.45%)
      D: 46.2GiB / 232.9GiB (19.86%)

---

I installed through pip and just copied the command in the readme so I'm probably using the latest version

**Comment by BlivionIaG** [comment]
Oh right i found the bug, it's something that has been fixed, it works on current master, but need to be updated on pip.

**Comment by BennoMP** [comment]
Ok. Thanks

**Comment by BlivionIaG** [comment]
I don't have access to pip so i'll talk about it with the other developpers for a new hotfix release.

**Comment by BennoMP** [comment]
Let me know when it has been updated :D

**Comment by BlivionIaG** [comment]
So I finally got access on pip credentials, it's updated now :)

**Comment by BennoMP** [comment]
Awesome, thanks!
