### ISSUE TITLE
Add Support for Devuan

### ISSUE THREAD

**Issue by PrimeDoppel** [MrPotatoBobx/FetchCord#89]
# Debug info
laptop: True
----out.py----

----DE/WM----
deid: Xfce
wmid: Xfwm4
wmline item 0: WM: Xfwm4 

----TERMINAL----

fontline: Terminal Font: Monospace 12 
termid: xfce4-terminal
termline item 0: Terminal: xfce4-terminal 
themeline: WM Theme: Arc-Dark 
Theme: Arc-Dark [GTK2], Adwaita [GTK3] 

----HOST INFO----

hostline: ['Host: 355V4C/355V4X/355V5C/355V5X/356V4C/356V4X/356V5C/356V5X/3445VC/3445VX/3545VC/3545VX P04ABG.007.CP ']

----GPU INFO----

gpuinfo: GPU: AMD PALM 
gpuvendor: AMD

----CPU INFO----

cpuvendor: AMD
cpumodel: E2-1800 APU
cpuinfo: CPU: AMD E2-1800 APU (2) @ 1.700GHz
cpuline item 0: CPU: AMD E2-1800 APU (2) @ 1.700GHz 
memline: Memory: 2837MiB / 5408MiB

----OS INFO----

sysosline: ['OS: Devuan GNU/Linux 4 (chimaera/ceres) x86_64 ']
sysosid: Devuan
packagesline item 0: Packages: 2285 (dpkg), 5 (flatpak) 
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact us on the GitHub page to resolve this.(keyerror)
unknown CPU, contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: Xfce
wmid: Xfwm4

----TERMINAL/SHELL----

termid: xfce4-terminal
shellid: bash

----HOST INFO----

hostid: VC/VX/VC/VX/VC/VX/VC/VX/VC/VX/VC/VX

----GPU INFO----

gpuvendor: AMD

----CPU INFO----

cpumodel: E2-1800 APU

# Requested item

Please add support for Devuan. it's effectively debian, but without systemd.

**Comment by MrPotatoBobx** [comment]
are you okay with us just pointing it to debian rpc?

**Comment by PrimeDoppel** [comment]
I'm okay with that, since devuan is basically a simple change from debian.

**Comment by Hyper-KVM** [comment]
Done, do --update

**Comment by MrPotatoBobx** [comment]
if you have any issues with devuan on fetchcord feel free to make a new issue
