### ISSUE TITLE
Running in terminal works but not as a systemd service

### ISSUE THREAD

**Issue by Nathan13888** [MrPotatoBobx/FetchCord#91]
# Debug info

`fetchcord --debug`
```
laptop: False
----out.py----

----DE/WM----
deid: GNOME
wmid: Mutter
wmline item 0: WM: Mutter 

----TERMINAL----

fontline: Font: Fira Sans Semi-Light 11 [GTK2/3]
termid: guake
termline item 0: Terminal: guake 
themeline: WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 

----HOST INFO----

hostline: ['Host: N/A']

----GPU INFO----

gpuinfo: GPU: NVIDIA GeForce GTX 950 [55°C]
gpuvendor: NVIDIA

----CPU INFO----

cpuvendor: Intel
cpumodel: Intel i5
cpuinfo: CPU: Intel i5-6400 (4) @ 3.300GHz
cpuline item 0: CPU: Intel i5-6400 (4) @ 3.300GHz 
memline: Memory: 4348MiB / 15947MiB 

----OS INFO----

sysosline: ['OS: Pop!_OS 20.04 LTS x86_64 ']
sysosid: Pop!_OS
diskline: Disk (/): 94G / 102G (98%) 
packagesline item 0: Packages: 3076 (dpkg), 1 (pkg), 8 (flatpak), 3 (snap) 
Unknown shell, contact us on github to resolve this.
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: GNOME
wmid: Mutter

----TERMINAL/SHELL----

termid: guake
shellid: unknown

----HOST INFO----

hostid: N/A

----GPU INFO----

gpuvendor: NVIDIA

----CPU INFO----

cpumodel: Intel i5

Connecting
----run_rpc----

uptime in epoch: 1599050818.0
cpuid: 740660055925587978
cpuappid: 741099939198926920
termappid: 745691250186911796
hostappid: 742887089179197462
Packages: 3076 (dpkg), 1 (pkg), 8 (flatpak), 3 (snap) 
RPC Connection Successful.
cycle 0
appid: 740660055925587978
cycle 1
appid: 741099939198926920
cycle 2
appid: 745691250186911796
cycle 0
appid: 740660055925587978
cycle 1
appid: 741099939198926920

cycle 2
appid: 745691250186911796
cycle 0
appid: 740660055925587978
cycle 1
appid: 741099939198926920
cycle 2
appid: 745691250186911796
cycle 0
appid: 740660055925587978
cycle 1
appid: 741099939198926920
cycle 2
appid: 745691250186911796
cycle 0
appid: 740660055925587978
cycle 1
appid: 741099939198926920
cycle 2
appid: 745691250186911796
```

# Operating system & way of installation

Pop OS 20.04, PIP (followed the steps for Linux in README)

# Error/issue

**Problem Description**
Running directly from a terminal seems to work and does not crash (ie. opening a terminal and running it there). But trying to run fetchcord as a service seems to error out. Perhaps some of the stacktrace logs might help.

I've also attached an image of fetchcord.service. I've tried changing the command in which the service runs but that doesn't seem to affect the error message.

**error status from systemctl**
![image](https://user-images.githubusercontent.com/29968201/91990321-95aa4100-ecff-11ea-82b6-a827e406fac7.png)

![image](https://user-images.githubusercontent.com/29968201/91990433-b4a8d300-ecff-11ea-89c8-c355ca4afa38.png)

**Comment by MrPotatoBobx** [comment]
@BlivionIaG made the systemd service, migtt want to check this out

**Comment by Nathan13888** [comment]
It's been 12 days already. Does any one have a clue?

**Comment by MrPotatoBobx** [comment]
try fetchcord 2.7

**Comment by Nathan13888** [comment]
Alright I just tried the latest git version and the systemctl service seems to work now. Also I noticed some other some things that could be potential improvements or fixes.

Btw, this is the Arch version I'm using rn.

I'll submit another issue in the next few days if there's a need for that.
