### ISSUE TITLE
Unknown Host & Terminal (Manjaro&Terminator&zsh)

### ISSUE THREAD

**Issue by vertolet-git** [MrPotatoBobx/FetchCord#97]
# Debug info

**
laptop: False
----out.py----

----DE/WM----
deid: Plasma
wmid: KWin
wmline item 0: WM: KWin 

----TERMINAL----

fontline: Terminal Font: N/A
Font: N/A
termid: terminator
termline item 0: Terminal: terminator 
themeline: WM Theme: plastik 
Theme: Breath2 [Plasma], Breath [GTK2/3] 

----HOST INFO----

hostline: ['Host: N/A']

----GPU INFO----

gpuinfo: GPU: NVIDIA GeForce GTX 1070 Ti [34°C]
gpuvendor: NVIDIA

----CPU INFO----

cpuvendor: Intel
cpumodel: Intel i7
cpuinfo: CPU: Intel i7-8700K (12) @ 4.700GHz
cpuline item 0: CPU: Intel i7-8700K (12) @ 4.700GHz 
memline: Memory: 3533MiB / 15941MiB 

----OS INFO----

sysosline: ['OS: Manjaro Linux x86_64 ']
sysosid: Manjaro
packagesline item 0: Packages: 1411 (pacman), 9 (flatpak) 
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: Plasma
wmid: KWin

----TERMINAL/SHELL----

termid: terminator
shellid: zsh

----HOST INFO----

hostid: N/A

----GPU INFO----

gpuvendor: NVIDIA

----CPU INFO----

cpumodel: Intel i7

Connecting
----run_rpc----

uptime in epoch: 1600764896.0
cpuid: 740614258177605642
cpuappid: 741100300219187335
termappid: 745691250186911796
hostappid: 742887089179197462
Packages: 1411 (pacman), 9 (flatpak) 
RPC Connection Successful.
cycle 0
appid: 740614258177605642
cycle 1
appid: 741100300219187335
cycle 2
appid: 745691250186911796
cycle 0
appid: 740614258177605642
cycle 1
appid: 741100300219187335
cycle 2
appid: 745691250186911796
**

# Operating system & way of installation

**Manjaro - Installed using AUR**

# Error/issue

**Unknown Host
Unsupported Terminal**

# Other notes(optional)

**Discord is also installed using the AUR at http://aur.archlinux.org/packages/discord_arch_electron**

Feel free to contact me on Discord in "The Terminal Cafe" if you like

**Comment by MrPotatoBobx** [comment]
i'll look into this

**Comment by MrPotatoBobx** [comment]
try using pip, and fetchcord 2.7

**Comment by potatoekun** [comment]
Done, still some errors popping up but this time a bit different. Type is some form of KeyError
Tried it both with pip and with AUR again

**Using PIP**
_Message on run_

fetchcord
[KeyError]: 'Font:'[KeyError]: 'Font:'[KeyError]: 'Host:'
('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
[KeyError]: 'Host:'
Unknown motherboard, contact us on github to resolve this.

_--debug_

fetchcord --debug
[KeyError]: 'Font:'[KeyError]: 'Font:'[KeyError]: 'Host:'
----run_rpc----

uptime in epoch: 1609075687.0
cpuid: 740614258177605642
cpuappid: 741100300219187335
termappid: 741291339945345045
[KeyError]: 'Host:'
1621 (pacman), 15 (flatpak)
----out.py----

----DE/WM----
deid: Plasma
wmid: KWin
wmline item 0: KWin

----TERMINAL----

[KeyError]: 'Font:'
fontline: Font: N/A
termid: 741291339945345045
termline item 0: alacritty
themeline: plastik
Breath2 [Plasma], Breath [GTK2/3]
[KeyError]: 'Host:'

----GPU INFO----

gpuinfo: NVIDIA GeForce GTX 1070 Ti
gpuvendor: nvidia

----CPU INFO----

cpuvendor: intel
cpumodel: Intel i7
cpuinfo: Intel i7-8700K (12) @ 4.700GHz
cpuline item 0: Intel i7-8700K (12) @ 4.700GHz
memline: 4750MiB / 15941MiB

----OS INFO----

sysosline: Manjaro Linux x86_64
sysosid: 740614258177605642
[KeyError]: 'Disk'
diskline: Disk N/A
packagesline item 0: 1621 (pacman), 15 (flatpak)

----testing.py----
----DE/WM----

deid: Plasma
wmid: KWin

----TERMINAL/SHELL----

termid: 741291339945345045
shellid: zsh

----HOST INFO----

[KeyError]: 'Host:'
[KeyError]: 'Host:'
hostid: 742887089179197462

----GPU INFO----

gpuvendor: nvidia

----CPU INFO----

cpumodel: Intel i7

('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
[KeyError]: 'Host:'
Unknown motherboard, contact us on github to resolve this.
{}
cycle0 not in : True
try_connect(key="cycle0") on <pypresence.presence.Presence object at 0x7f20eab11490>
cycle 0
try_update(key="cycle0") on <pypresence.presence.Presence object at 0x7f20eab11490>
appid: 740614258177605642


**Using AUR**
_Message on run_

fetchcord
[KeyError]: 'Font:'[KeyError]: 'Font:'[KeyError]: 'Host:'
('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
[KeyError]: 'Host:'
Unknown motherboard, contact us on github to resolve this.

_--debug_

fetchcord --debug
[KeyError]: 'Font:'[KeyError]: 'Font:'[KeyError]: 'Host:'
----run_rpc----

uptime in epoch: 1609075687.0
cpuid: 740614258177605642
cpuappid: 741100300219187335
termappid: 741291339945345045
[KeyError]: 'Host:'
1623 (pacman), 15 (flatpak)
----out.py----

----DE/WM----
deid: Plasma
wmid: KWin
wmline item 0: KWin

----TERMINAL----

[KeyError]: 'Font:'
fontline: Font: N/A
termid: 741291339945345045
termline item 0: alacritty
themeline: plastik
Breath2 [Plasma], Breath [GTK2/3]
[KeyError]: 'Host:'

----GPU INFO----

gpuinfo: NVIDIA GeForce GTX 1070 Ti
gpuvendor: nvidia

----CPU INFO----

cpuvendor: intel
cpumodel: Intel i7
cpuinfo: Intel i7-8700K (12) @ 4.700GHz
cpuline item 0: Intel i7-8700K (12) @ 4.700GHz
memline: 4897MiB / 15941MiB

----OS INFO----

sysosline: Manjaro Linux x86_64
sysosid: 740614258177605642
[KeyError]: 'Disk'
diskline: Disk N/A
packagesline item 0: 1623 (pacman), 15 (flatpak)

----testing.py----
----DE/WM----

deid: Plasma
wmid: KWin

----TERMINAL/SHELL----

termid: 741291339945345045
shellid: zsh

----HOST INFO----

[KeyError]: 'Host:'
[KeyError]: 'Host:'
hostid: 742887089179197462

----GPU INFO----

gpuvendor: nvidia

----CPU INFO----

cpumodel: Intel i7

('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
[KeyError]: 'Host:'
Unknown motherboard, contact us on github to resolve this.
{}
cycle0 not in : True
try_connect(key="cycle0") on <pypresence.presence.Presence object at 0x7fbe4e7f3670>
cycle 0
try_update(key="cycle0") on <pypresence.presence.Presence object at 0x7fbe4e7f3670>
appid: 740614258177605642

**Comment by BlivionIaG** [comment]
Hello, can I get the neofetch output ? And can you try the latest version ?

**Comment by BlivionIaG** [comment]
Well i guess i'm closing this, feel free to check latest versions.
