### ISSUE TITLE
--termfont option does not work when run from script/i3 config

### ISSUE THREAD

**Issue by brokenbyte** [MrPotatoBobx/FetchCord#99]
# Debug info

laptop: True
Custom terminal font not set because a terminal font already exists, Terminal Font: JetBrains Mono 13.0 
----out.py----

----DE/WM----
deid: N/A
wmid: i3
wmline item 0: WM: i3 

----TERMINAL----

fontline: Terminal Font: JetBrains Mono 13.0 
termid: kitty
termline item 0: Terminal: kitty 
themeline: Theme: Adwaita [GTK2/3] 

----HOST INFO----

hostline: ['Host: Gazelle gaze14 ']

----GPU INFO----

gpuinfo: GPU: Intel UHD Graphics 630 
gpuvendor: Intel

----CPU INFO----

cpuvendor: Intel
cpumodel: Intel i7
cpuinfo: CPU: Intel i7-9750H (12) @ 4.500GHz
cpuline item 0: CPU: Intel i7-9750H (12) @ 4.500GHz 
memline: Memory: 2.31GiB / 15.35GiB 

----OS INFO----

sysosline: ['OS: Arch Linux x86_64 ']
sysosid: Arch
packagesline item 0: Packages: 1949 (pacman), 5 (flatpak) 
Unknown Host, contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: N/A
wmid: i3

----TERMINAL/SHELL----

termid: kitty
shellid: zsh

----HOST INFO----

hostid: Gazelle

----GPU INFO----

gpuvendor: Intel

----CPU INFO----

cpumodel: Intel i7

Connecting
----run_rpc----

uptime in epoch: 1601317259.0
cpuid: 740476198437650473
cpuappid: 741100300219187335
termappid: 741285676250824725
hostappid: 742887089179197462
Packages: 1949 (pacman), 5 (flatpak) 
RPC Connection Successful.
cycle 0
appid: 740476198437650473
cycle 1
appid: 741100300219187335
# Operating system & way of installation

Arch Linux, both pip and AUR
# Error/issue
When running fetchcord from a script/i3 config, using the `--termfont` option still shows the font as "N/A".
I stuck the following in a shell script to produce the issue:
```sh
#!/bin/bash
fetchcord --time 15 --terminal 'kitty' --termfont 'Jetbrains Mono 13.0' --debug&
```
The same thing happens when starting from i3 config, but if I run the line manually from a terminal it works fine.
# Other notes(optional)

![image](https://user-images.githubusercontent.com/37650823/94574409-f1e18180-0227-11eb-85f2-d2cc56975147.png)

**Comment by MrPotatoBobx** [comment]
might've been a code error, see `fontline: Terminal Font: JetBrains Mono 13.0` should be fixed in 2.7
